# Message of the bounding box for detected object

uint64 					id					# Id of the object detected
string 					Class				# Class of the object
float64 				probability			# Probability of the object
int64 					xmin				# Upper left x corner of the bounding box
int64 					ymin				# Upper left y corner of the bounding box
int64 					xmax				# Lower right x corner of the bounding box
int64 					ymax				# Lower right y corner of the bounding box
